// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh8GdUQyQS3Q32uhH-0LHeEyjHreH0ii0',
    appId: '1:385911842801:web:8d5bf99bfbc818f4c98650',
    messagingSenderId: '385911842801',
    projectId: 'newsapp-92989',
    authDomain: 'newsapp-92989.firebaseapp.com',
    storageBucket: 'newsapp-92989.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0us6TgA62k7LB0R-ZTESnNMqbKeolr6M',
    appId: '1:385911842801:android:65a3a686725fcfecc98650',
    messagingSenderId: '385911842801',
    projectId: 'newsapp-92989',
    storageBucket: 'newsapp-92989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoewe-w1SIrkaSR_A7_W5L-odlvxoKTV0',
    appId: '1:385911842801:ios:6c1d572e00ea29a8c98650',
    messagingSenderId: '385911842801',
    projectId: 'newsapp-92989',
    storageBucket: 'newsapp-92989.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoewe-w1SIrkaSR_A7_W5L-odlvxoKTV0',
    appId: '1:385911842801:ios:6c1d572e00ea29a8c98650',
    messagingSenderId: '385911842801',
    projectId: 'newsapp-92989',
    storageBucket: 'newsapp-92989.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh8GdUQyQS3Q32uhH-0LHeEyjHreH0ii0',
    appId: '1:385911842801:web:82c2a78e1c26c095c98650',
    messagingSenderId: '385911842801',
    projectId: 'newsapp-92989',
    authDomain: 'newsapp-92989.firebaseapp.com',
    storageBucket: 'newsapp-92989.firebasestorage.app',
  );
}
